### ISSUE TITLE
Remove Searchbox from Homepage

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/openlist-website#1]
We have a search box on the homepage that doesn't actually do anything. If you would like to remove it, that would be awesome!

If you would like to claim this issue, leave a comment below and I will assign it to you. I can also explain the best way to implement this if you would like.

**Comment by William-McGonagle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove Searchbox from Homepage](https://trello.com/c/9aKWvIl9/28-remove-searchbox-from-homepage)

**Comment by Aditya-A-G** [comment]
hey, I would like to work on this issue and also would love to hear your explanation to implement this

**Comment by iambharathpadhu** [comment]
Hey even i would like to contribute !

**Comment by William-McGonagle** [comment]
Hi @Aditya-A-G @iambharathpadhu – I'll assign you both, please make a PR! :smile:
