### ISSUE TITLE
Fix the SEO on the License Pages

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/openlist-website#3]
It would be really great if we could add questions to each of the license pages, such as 'does [insert license here] license support modification?' because these questions will then be processed by Google and anyone that searches that will find the license list as the first result.

If you would like to claim this issue, leave a comment below and I will assign it to you. I can also explain the best way to implement this if you would like.

**Comment by William-McGonagle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Include better SEO](https://trello.com/c/oyFfxXJd/19-include-better-seo)

**Comment by Aditya-A-G** [comment]
hey, i would like to work on this issue

**Comment by William-McGonagle** [comment]
Sounds good– I'll assign you!

**Comment by William-McGonagle** [comment]
Hey @Aditya-A-G – you should check you #8

**Comment by Aditya-A-G** [comment]
Sure
