### ISSUE TITLE
Add Google Structured Data for Questions

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/openlist-website#8]
Hey there!

Right now, we have a questions panel on each OpenList license page, but it would be even better if we could have structured data so that search engines and bots can understand the licenses (this will help our SEO). We would be using [this structured data](https://developers.google.com/search/docs/appearance/structured-data/faqpage) in order to let bots understand the page. If you are interested in taking this issue, you pretty much just need to convert JSON to a string and use 'dangerouslySetInnerHTML' on a script to get the same behavior that a script tag (with JSON type) would have.

If you are interested in taking this issue, please let me know in the comments below. 

Cheers,
William McGonagle

**Comment by Aditya-A-G** [comment]
I would like to work on this issue

**Comment by William-McGonagle** [comment]
Sounds good- I'll assign you!
